language: c

cache:
  directories:
    - tundra
    - vbcc

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - export PATH=$PATH:$PWD/tundra/bin
  - export VBCC=$PWD/vbcc

install:
  - [ ! -f tundra/bin/tundra2 ] && git clone --recurse-submodules https://github.com/deplinenoise/tundra.git t2-build && cd t2-build && make && PREFIX=$PWD/../tundra make install
  - [ ! -f vbcc/bin/vbccm68k ] && ./build_vbcc.sh

script:
  - tundra2 release
  - tundra2 -j 1 amiga-vbcc-release
