language: c

cache:
  directories:
    - vbcc

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - git clone --recurse-submodules git://github.com:deplinenoise/tundra.git
  - cd tundra && make && make install

install:
  - ./build_vbcc.sh

script:
  - tundra2 release
  - VBCC=$PWD/vbcc tundra2 -j 1 amiga-vbcc-release
