name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: apt install
      run: sudo apt-get install wget p7zip-full
    - name: build all
      run: ./build_all.sh

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: brew install
      run: brew install wget p7zip
    - name: build all
      run: ./build_all.sh
